export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const UPDATE_FEED = 'UPDATE_FEED';

export const REQUEST_FEED_PENDING = 'REQUEST_FEED_PENDING';
export const REQUEST_ESPN_FEED_SUCCESS = 'REQUEST_ESPN_FEED_SUCCESS';
export const REQUEST_EUROLEAGUE_FEED_SUCCESS = 'REQUEST_EUROLEAGUE_FEED_SUCCESS';
export const REQUEST_TALKBASKET_FEED_SUCCESS = 'REQUEST_TALKBASKET_FEED_SUCCESS';
export const REQUEST_FEED_FAILED = 'REQUEST_FEED_FAILED';

